package projectdir

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/riipandi/elph/internal/appdir"
)

const (
	// RelRoot is the project-local Elph directory relative to the workspace root.
	RelRoot = ".agents/elph"

	gitignoreName = ".gitignore"
	gitignoreBody = "" +
		"# Generated by Elph agent (DO NOT REMOVE!!)\n" +
		".gitignore\n" +
		"metadata/\n" +
		"prompts/\n" +
		"settings.json*\n" +
		"mcp.json*\n"
)

var gitignoreRequiredEntries = []string{
	".gitignore",
	"metadata/",
	"prompts/",
	"settings.json*",
	"mcp.json*",
}

// Root returns <workDir>/.agents/elph.
func Root(workDir string) string {
	return filepath.Join(workDir, ".agents", "elph")
}

// PromptsDir returns <workDir>/.agents/elph/prompts.
func PromptsDir(workDir string) string {
	return filepath.Join(Root(workDir), "prompts")
}

// SkillsDir returns <workDir>/.agents/elph/skills.
func SkillsDir(workDir string) string {
	return filepath.Join(Root(workDir), "skills")
}

// MetadataDir returns <workDir>/.agents/elph/metadata.
func MetadataDir(workDir string) string {
	return filepath.Join(Root(workDir), "metadata")
}

// SessionMetadataDir returns <workDir>/.agents/elph/metadata/<sessionID>.
func SessionMetadataDir(workDir, sessionID string) string {
	return filepath.Join(MetadataDir(workDir), sessionID)
}

// SessionTodosPath returns <workDir>/.agents/elph/metadata/<sessionID>/todos.jsonl.
func SessionTodosPath(workDir, sessionID string) string {
	return filepath.Join(SessionMetadataDir(workDir, sessionID), "todos.jsonl")
}

// AttachmentsDir returns ~/.local/share/elph/attachments.
func AttachmentsDir(workDir string) string {
	dir, err := appdir.AttachmentsDir()
	if err != nil {
		// Fallback to project-local if appdir fails
		return filepath.Join(Root(workDir), "attachments")
	}
	return dir
}

// EnsureRoot creates <workDir>/.agents/elph and writes .gitignore when missing.
func EnsureRoot(workDir string) error {
	root := Root(workDir)
	if err := os.MkdirAll(root, 0o755); err != nil {
		return err
	}
	return ensureGitignore(root)
}

// EnsureSessionMetadataDir creates metadata/<sessionID>/ under the Elph root.
func EnsureSessionMetadataDir(workDir, sessionID string) error {
	if workDir == "" || sessionID == "" {
		return nil
	}
	if err := EnsureRoot(workDir); err != nil {
		return err
	}
	return os.MkdirAll(SessionMetadataDir(workDir, sessionID), 0o755)
}

func ensureGitignore(root string) error {
	path := filepath.Join(root, gitignoreName)
	raw, err := os.ReadFile(path)
	if err == nil {
		if gitignoreUpToDate(string(raw)) {
			return nil
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	return os.WriteFile(path, []byte(gitignoreBody), 0o600)
}

func gitignoreUpToDate(content string) bool {
	for _, entry := range gitignoreRequiredEntries {
		if !strings.Contains(content, entry) {
			return false
		}
	}
	return true
}
